### ISSUE TITLE
Get Deepak and Vinay on board!!

### ISSUE THREAD

**Issue by prerit912** [prerit912/Datathon#1]
@vinayvrv Deepak doesn't have a github profile

**Comment by prerit912** [comment]
@kotrikedeepak I don't know if vinay is joining our team, but we definitely want him to collaborate.

**Comment by kotrikedeepak** [comment]
@prerit912 Get him what he want's and he would collaborate with us for sure !

**Comment by prerit912** [comment]
@kotrikedeepak  Closing the issue, Vinay is not interested. But if he is we can have him up and running at anytime.
