### ISSUE TITLE
Getting Time Series Project from Kaggle.

### ISSUE THREAD

**Issue by prerit912** [prerit912/Datathon#2]

**Comment by kotrikedeepak** [comment]
[S & P 500 Companies](https://www.kaggle.com/dgawlik/nyse)
[Crypto](https://www.kaggle.com/jessevent/all-crypto-currencies)
[Bitcoin historical data](https://www.kaggle.com/mczielinski/bitcoin-historical-data)

I shall try to look for some more datasets as well !

**Comment by prerit912** [comment]
Ok let's finalize on Bitcon Historical data, it's a good choice. Hope we can find some value with this project.
